CREATE TABLE IF NOT EXISTS customers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(150) NOT NULL,
    city VARCHAR(80) NOT NULL,
    age INTEGER NOT NULL CHECK (age BETWEEN 18 AND 120),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
